import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
  ]),
  {
    // zod must come from src/lib/zod.ts, which turns off its eval probe before
    // any schema exists. A direct import could build a schema first, and the
    // Content-Security-Policy would report the blocked probe on every page.
    files: ["src/**/*.{ts,tsx}"],
    ignores: ["src/lib/zod.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "zod",
              message: 'Import { z } from "@/lib/zod" — it disables zod\'s eval probe, which the CSP blocks.',
            },
          ],
        },
      ],
    },
  },
  {
    /**
     * Generated by the shadcn CLI, never hand-written — so these cannot be
     * fixed here without the next `shadcn add` reverting them.
     *
     * Both violations are real but upstream: `sidebar.tsx` calls `Math.random()`
     * for the skeleton width, and `use-mobile.ts` seeds its state inside an
     * effect. Neither affects correctness in this app (the skeleton is
     * decorative; the mobile flag resolves on the first paint), so they are
     * scoped off rather than silenced globally.
     */
    files: ["src/components/ui/**/*.tsx", "src/hooks/use-mobile.ts"],
    rules: {
      "react-hooks/purity": "off",
      "react-hooks/set-state-in-effect": "off",
    },
  },
]);

export default eslintConfig;
