import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
  ]),
  {
    /**
     * Generated by the shadcn CLI, never hand-written — so these cannot be
     * fixed here without the next `shadcn add` reverting them.
     *
     * Both violations are real but upstream: `sidebar.tsx` calls `Math.random()`
     * for the skeleton width, and `use-mobile.ts` seeds its state inside an
     * effect. Neither affects correctness in this app (the skeleton is
     * decorative; the mobile flag resolves on the first paint), so they are
     * scoped off rather than silenced globally.
     */
    files: ["src/components/ui/**/*.tsx", "src/hooks/use-mobile.ts"],
    rules: {
      "react-hooks/purity": "off",
      "react-hooks/set-state-in-effect": "off",
    },
  },
]);

export default eslintConfig;
